version: 2
jobs:
  "RxKingfisher CI":
    working_directory: ~/RxSwiftCommunity/RxKingfisher
    parallelism: 1
    shell: /bin/bash --login
    environment:
      XCODE_TEST_REPORTS: /tmp/xcode-test-results
      LANG: en_US.UTF-8
    macos:
      xcode: '12.1'
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS $XCODE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run: 
          name: Bootstrap Carthage
          command: scripts/bootstrap-if-needed.sh
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - Carthage
      - run:
          name: macOS, Swift 5.0
          command: set -o pipefail && xcodebuild build SWIFT_VERSION=5.0 -scheme RxKingfisher-macOS -project RxKingfisher.xcodeproj -sdk macosx -destination "arch=x86_64" | xcpretty
      - run:
          name: iOS, Swift 5.0
          command: set -o pipefail && xcodebuild build SWIFT_VERSION=5.0 -scheme RxKingfisher-iOS -project RxKingfisher.xcodeproj -sdk iphonesimulator -destination "name=iPhone X" | xcpretty
      - run:
          name: Build tvOS, Swift 5.0
          command: set -o pipefail && xcodebuild build SWIFT_VERSION=5.0 -scheme RxKingfisher-tvOS -project RxKingfisher.xcodeproj -sdk appletvsimulator -destination "name=Apple TV 4K (at 1080p)" | xcpretty
      - store_artifacts:
          path: $XCODE_TEST_REPORTS
  "RxKingfisher Release":
    working_directory: ~/RxSwiftCommunity/RxKingfisher
    parallelism: 1
    shell: /bin/bash --login
    environment:
      LANG: en_US.UTF-8
    macos:
      xcode: '12.1'
    steps:
      - checkout
      - run:
          name: Setup CocoaPods
          command: pod setup
      - run:
          name: Override Circle CI Config
          command: rm ~/.cocoapods/config.yaml # This hack is needed since CircleCI forces --verbose
      - run:
          name: Push Podspec to Trunk
          command: pod trunk push --swift-version=5×¥0 --skip-tests --allow-warnings
workflows:
  version: 2
  build:
    jobs:
      - "RxKingfisher CI":
          filters:
            tags:
              ignore: /[0-9]+(\.[0-9]+)*/
  release:
    jobs:
      - "RxKingfisher Release":
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
